In [18]:
import torch
import numpy as np
import torch.nn as nn
import time
device='cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [2]:
randint=torch.randint(-100,100,(6,))
randint

tensor([-97, -88, -42,   8, -40,  88])

In [3]:
tensor=torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
zeros=torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones=torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
input=torch.empty(2,3)
input

tensor([[6.2119e-33, 1.8371e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [7]:
arange=torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
linspace=torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
logspace=torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [10]:
eye=torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
a= torch.empty((2,3),dtype=torch.int64)
empty_like=torch.empty_like(a)
empty_like

tensor([[5630869903344,             0,             0],
        [            0,             0,             0]])

In [17]:
#Define a probability tensor
probabilities=torch.tensor([0.1,0.9])
#10% or 0.1=> 0, 90% or 0.9=> 1, each probability points to the index of the probability in the tensor
#Draw 5 samples from the multinomial distribution
samples=torch.multinomial(probabilities,num_samples=10, replacement=True)
print(samples)

tensor([1, 0, 1, 0, 1, 1, 1, 1, 1, 1])


In [18]:
tensor=torch.tensor([1,2,3,4])
out=torch.cat((tensor,torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [3]:
out=torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [4]:
out=torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [5]:
out=torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [6]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [7]:
input=torch.zeros(2,3,4)
out=input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [8]:
tensor1=torch.tensor([1,2,3])
tensor2=torch.tensor([4,5,6])
tensor3=torch.tensor([7,8,9])
#STACK THE TENSORS ALONG WITH A NEW DIMENSION
stacked_tensor=torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
import torch.nn as nn
sample=torch.tensor([10.,10.,10.])
linear=nn.Linear(3,3,bias=False)
print(linear(sample))

tensor([-6.8905, 10.6466,  8.5156], grad_fn=<SqueezeBackward4>)


In [12]:
import torch.nn.functional as F
#Create a tensor
tensor1=torch.tensor([1.0,2.0,3.0])
#Apply softmax using torch.nn.functional.softmax()
softmax_output=F.softmax(tensor1,dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [15]:

# Create an Embedding layer with 10 possible indices (e.g., words) and embedding dimension of 3
embedding = nn.Embedding(num_embeddings=1000, embedding_dim=100)

# Indices of words
input_indices = torch.tensor([1,5,3,2])

# Get the embeddings for the input indices
embedded_output = embedding(input_indices)

print(embedded_output.shape)


torch.Size([4, 100])


In [20]:
a=torch.tensor([[1,2],[3,4],[5,6]])
b=torch.tensor([[7,8,9],[10,11,12]])
print(a@b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [24]:
int_64=torch.randint(1,(3,2)).float()
#type int64
float_32=torch.rand(2,3)
#type float32
result=torch.matmul(int_64,float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [28]:
input=torch.rand((4,8,10))
B,T,C=input.shape
output=input.view(B*T, C)
print(output)
#print(output[:, -1, :])

tensor([[0.8439, 0.4524, 0.1650, 0.8630, 0.4450, 0.4017, 0.2663, 0.0658, 0.6380,
         0.3474],
        [0.2944, 0.8239, 0.2148, 0.0934, 0.8850, 0.3611, 0.3137, 0.4010, 0.7245,
         0.4809],
        [0.2102, 0.9480, 0.8437, 0.3304, 0.1703, 0.7518, 0.4217, 0.4104, 0.3668,
         0.3932],
        [0.2710, 0.2595, 0.3609, 0.1406, 0.4315, 0.4987, 0.1931, 0.1668, 0.2400,
         0.0805],
        [0.6699, 0.8658, 0.1539, 0.8139, 0.3451, 0.2158, 0.1443, 0.2564, 0.5979,
         0.5622],
        [0.3398, 0.8349, 0.9084, 0.1306, 0.6157, 0.7605, 0.6026, 0.2015, 0.3269,
         0.2197],
        [0.2573, 0.5832, 0.2869, 0.4147, 0.3523, 0.5876, 0.0676, 0.5097, 0.1407,
         0.6584],
        [0.9398, 0.7872, 0.5128, 0.7338, 0.6465, 0.9132, 0.7260, 0.6021, 0.6167,
         0.7407],
        [0.9361, 0.2616, 0.3885, 0.3823, 0.2587, 0.5880, 0.5009, 0.2453, 0.8547,
         0.8377],
        [0.8970, 0.3933, 0.3735, 0.5502, 0.2074, 0.0916, 0.6371, 0.3670, 0.6447,
         0.9778],
        [0

In [32]:
x=torch.tensor([10], dtype=torch.float32)
y=F.tanh(x)
print(y)

tensor([1.])
